travis:
  secure:
    BINSTAR_TOKEN: CcneBUmG1Eq7y3rL0kw0b+3AzKn9ZqGk/NHPXHuMX0ajg6vA+u7RtdXAmxUsiAZ4E6yPfijvDYbZwvL/im3aFAf+XFruUZdLolPuaxNzOyHq+AQMGrN6JTF57wyQHr+vrdx11EkqEozouLoBQkAPph+hiDvIDEjCXUkn7UDNTTjV0MMTSMIw021c2o4//chixZn77h9jzYzDZ5bYKwpH8AhjfwHf3MEu4fKaQLzQRnLpCYm7316c+NolO6Kkh+WMQJEgrvPKtMQw9pkU+ZOXfjxt011I0wfhNymITKLiT5hfGVFMqBZtJQcybbuLgf3C5t8PtCIw3tp4ggb8TKwX6Hw66kZ9O7679hCn6AvaWpD6BBdQVmv0QSvTWllF/Gs7J13qMOyq2NXHJmF3ZhHK5AAzBrBg+iSxs8U6x1ntls7G4yl5cZlJ32VgkRG277NcC2BU9l1vad+W3CmR7cy2E6yNKbo9h/tQgaykQq+JfW+d7cRR8SqQ9E4TmDo3p5gnt37QALykFIh2TxoGgF9DPyerW+lGDqq/PjDM5FUmm8V8KJah0+vvxivCXSTepueA45bdCLvjiKfoJUJxfsIN0vSkq6B2y0gnGcipCFKzwoyf7DpYi42jm6p3GThC3xFcTQvKeZlo47sSiGw1uhKuKTlr/krlS/A4j4GBiDc+hfE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
