travis:
  secure:
    BINSTAR_TOKEN: n+UzhjLyBWGcdH1oCV0cVFtjeRNcl2/IKS6hqOzXDmynouCyP4PYoOqvHT177NoUJZA7QsESddxlNyZ4xp+lVQfqVAE3oQABDoGYXJlpZsFtcBjOEApz+TLt80qAWeDDKJ5smFqVnEVqNJHcCeYKJy2ytQBtNdePmE3Pva8EVEpj7ffggBGjXb/p08cVQ+Hmhnr3Iqy5OAdCDnlkrm4ZhMRtF4s7GP8hApyWWkWPGB+iMN1bni5SNjiVmIYAN1z01i0WvaRKyK0YwCaXGzW0ZrUnIUxwhQswEWdFcs7ZmsJzDMTXUxzv31C1yXldHJPCx+VcQVx5ySFkfxwBWjMn2e1FVU1HiAzUZmJjIaZYtqUYpMyeQqMzlqBBtzv7XoTecj+TXNO0vl7+OCQOBH6pg+QL8aEGOKeb3mM1+38LBWZmYftSiVROzIy46LNLcR1EV6tjpR3BfClhR3cOvWg51APvnCf6l4u2Q1EwgXs6YYET/2Y3xK3Aqr6iMkSNyJxJaxLVw64h0O4jWpPMN21j3RAguEyD69BzU5nMp8oFzR0vWt0ZLourTXOD59wUiY/mBJbd0JEYRxiPdl/s8u/SATFwWiY5TgkYuXHS8TIkenxuCK1oZgLAjOJQuoA2AwkWCM3RfdS3+EdAiS7gdAaXlqwRt7qkSXVo6DCeHzgU/x0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
